/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

class SumCalculatorTests {
    private SumCalculator calculator;

    @BeforeEach
    void beforeEach(){
        calculator = new SumCalculator();
    }
    @Test
    void testThatSumWorksCorrect() {
        Map<Integer, Integer> testMap = new HashMap<>();
        testMap.put(6, 3);
        testMap.put(1, 1);
        testMap.put(15, 5);
        testMap.put(55, 10);
        testMap.put(5050, 100);

        testMap.forEach((expected,actual)-> Assertions.assertEquals(expected, calculator.sum(actual)));
    }
}
